import React from "react";

const analysisData = [
  {
    analysis: "Building Detection",
    location: "Anna Nagar",
    type: "Building",
    confidence: 96,
    status: "Verified"
  },
  {
    analysis: "Road Analysis",
    location: "KK Nagar",
    type: "Road",
    confidence: 91,
    status: "Verified"
  },
  {
    analysis: "Property Matching",
    location: "Tallakulam",
    type: "Property",
    confidence: 84,
    status: "Review"
  },
  {
    analysis: "Infrastructure Check",
    location: "Mattuthavani",
    type: "Infrastructure",
    confidence: 94,
    status: "Verified"
  }
];

function RecentAnalysis({
  location,
  assetType,
  status
}) {

  const filteredData = analysisData.filter((item) => {

    const locationMatch =
      location === "All Locations" ||
      item.location === location;

    const assetMatch =
      assetType === "All Assets" ||
      item.type === assetType;

    const statusMatch =
      status === "All Status" ||
      item.status === status;

    return locationMatch && assetMatch && statusMatch;
  });

  return (
    <div className="recent-analysis">

      <div className="section-header">
        <div>
          <h2>Recent AI Analysis</h2>

          <p>
            Latest results generated by UrbanLens AI.
          </p>
        </div>
      </div>

      <div className="analysis-table">

        <div className="analysis-header">
          <span>Analysis</span>
          <span>Location</span>
          <span>Type</span>
          <span>Confidence</span>
          <span>Status</span>
        </div>

        {filteredData.length > 0 ? (
          filteredData.map((item) => (
            <div
              className="analysis-row"
              key={item.analysis}
            >
              <span>{item.analysis}</span>

              <span>{item.location}</span>

              <span>{item.type}</span>

              <span>{item.confidence}%</span>

              <span
                className={
                  item.status === "Verified"
                    ? "status verified"
                    : "status review"
                }
              >
                {item.status}
              </span>
            </div>
          ))
        ) : (
          <div className="no-results">
            No analysis results found for the selected filters.
          </div>
        )}

      </div>

    </div>
  );
}

export default RecentAnalysis;